prometheus:
  prometheusSpec:
    enableRemoteWriteReceiver: true
    enableFeatures:
      - native-histograms
    tsdb:
      out_of_order_time_window: 8760h
    retention: 365d
    service:
      type: ClusterIP

  service:
    type: ClusterIP

grafana:
  enabled: true
  service:
    type: NodePort
    nodePort: 30300
  adminPassword: admin

  defaultDashboardsEnabled: false

alertmanager:
  enabled: false

nodeExporter:
  enabled: false

kubeStateMetrics:
  enabled: false

kubeApiServer:
  enabled: false

kubelet:
  enabled: false

kubeControllerManager:
  enabled: false

kubeScheduler:
  enabled: false

kubeProxy:
  enabled: false

kubeEtcd:
  enabled: false

coreDns:
  enabled: false

defaultRules:
  create: false
