mode: deployment

image:
  repository: otel/opentelemetry-collector-contrib
  tag: ""

config:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317

  exporters:
    prometheusremotewrite:
      endpoint: "http://kube-prometheus-stack-prometheus.monitoring:9090/api/v1/write"
      tls:
        insecure: true

  service:
    pipelines:
      metrics:
        receivers: [otlp]
        exporters: [prometheusremotewrite]

ports:
  otlp:
    enabled: true
    containerPort: 4317
    servicePort: 4317
    hostPort: 4317
    protocol: TCP
  otlp-http:
    enabled: false

service:
  type: NodePort

nodeSelector: {}
